fix restore

diff --git a/scripts/restore b/scripts/restore
--- a/scripts/restore
+++ b/scripts/restore
@@ -57,18 +57,17 @@ if [[ "$gitlab_edition" == "Enterprise" ]];then
 
 	chmod 755 $install_dir
 	# https://docs.gitlab.com/omnibus/settings/configuration.html#specify-the-external-url-at-the-time-of-installation
-	if ! EXTERNAL_URL="$generated_external_url" ynh_hide_warnings dpkg -i $tempdir/gitlab-ee.deb; then
+	if ! ynh_hide_warnings dpkg -i $tempdir/gitlab-ee.deb; then # This command will fail in lxc env
 		package_check_action
-		EXTERNAL_URL="$generated_external_url" ynh_hide_warnings dpkg --configure gitlab-ee
+		ynh_hide_warnings dpkg --configure gitlab-ee
 	fi
 else
 	ynh_setup_source --dest_dir=$tempdir --source_id="latest_$(lsb_release -sc)"
 
 	chmod 755 $install_dir
-	# https://docs.gitlab.com/omnibus/settings/configuration.html#specify-the-external-url-at-the-time-of-installation
-	if ! EXTERNAL_URL="$generated_external_url" ynh_hide_warnings dpkg -i $tempdir/gitlab-ce.deb; then
+	if ! ynh_hide_warnings dpkg -i $tempdir/gitlab-ce.deb; then # This command will fail in lxc env
 		package_check_action
-		EXTERNAL_URL="$generated_external_url" ynh_hide_warnings dpkg --configure gitlab-ce
+		ynh_hide_warnings dpkg --configure gitlab-ce
 	fi
 fi
 
