fix upgrade

diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -73,52 +73,94 @@ then
 
 	current_version=$(grep gitlab-ce /opt/gitlab/version-manifest.txt | cut -d' ' -f2)
 
-	# Load the last available version
-	source $YNH_APP_BASEDIR/scripts/upgrade.d/upgrade.last.sh
-	last_version=$gitlab_version
+	# Get Debian version
+	gitlab_debian_version="$(lsb_release -sc)"
 
-	source_next_version () {
-		# We start with the upgrade.$current_major_version.first.sh
-		if [ -e "$YNH_APP_BASEDIR/scripts/upgrade.d/upgrade.$current_major_version.first.sh" ]; then
-			source $YNH_APP_BASEDIR/scripts/upgrade.d/upgrade.$current_major_version.first.sh
-			if dpkg --compare-versions "$gitlab_version" "gt" "$current_version"; then
-				return
-			fi
+
+	# Function to get version from a source_id in manifest
+	get_version_from_source_id() {
+		local source_id=$1
+		local debian_version=$2
+
+		# Try to read from manifest for this Debian version
+		local section="resources.sources.${source_id}_${debian_version}"
+
+		if grep -q "\[${section}\]" "$YNH_APP_BASEDIR/manifest.toml"; then
+			# Extract URL to get version
+			local url=$(grep -A 10 "\[${section}\]" "$YNH_APP_BASEDIR/manifest.toml" | grep "amd64.url" | cut -d'"' -f2)
+			gitlab_version=$(echo "$url" | sed -n 's/.*gitlab-ce_\([0-9.]*\)-ce.0.*/\1/p')
+			gitlab_source_id="${source_id}_${debian_version}"
+			return 0
 		fi
 
-		# Then upgrade to all minor versions
-		for minor_verion in $(ls $YNH_APP_BASEDIR/scripts/upgrade.d/upgrade.$current_major_version* | grep -v -E ".first.sh$|.last.sh$" | sed -e "s@$YNH_APP_BASEDIR/scripts/upgrade.d/upgrade.$current_major_version.@@" -e "s/.sh$//" | sort)
-		do
-			source $YNH_APP_BASEDIR/scripts/upgrade.d/upgrade.$current_major_version.$minor_verion.sh
-			if dpkg --compare-versions "$gitlab_version" "gt" "$current_version"
-			then
-				return
+		return 1
+	}
+
+	# Function to get latest version
+	get_latest_version() {
+		local debian_version=$1
+		get_version_from_source_id "latest" "$debian_version"
+	}
+
+	# Function to list all available versions for upgrade path
+	list_upgrade_versions() {
+		local major_version=$1
+
+		# List all version IDs matching the pattern v{major}_*
+		grep -o "\[resources\.sources\.v${major_version}_[^]]*\]" "$YNH_APP_BASEDIR/manifest.toml" | \
+			sed 's/\[resources\.sources\.v//;s/\]//' | \
+			grep "^${major_version}_" | \
+			sed "s/_bookworm$//;s/_trixie$//;s/_bullseye$//" | \
+			sort -u | \
+			sed 's/_/\./g;s/^v//'
+	}
+
+	# Function to find and load next version in upgrade path
+	source_next_version() {
+		local current_major=${current_version%%.*}
+
+		# Get all versions for this major release
+		local versions=$(list_upgrade_versions "$current_major")
+
+		# Find the next version greater than current
+		local next_version=""
+		for ver in $versions; do
+			if dpkg --compare-versions "$ver" "gt" "$current_version"; then
+				next_version=$ver
+				break
 			fi
 		done
 
-		# Then end with upgrade.$current_major_version.last.sh
-		if [ -e "$YNH_APP_BASEDIR/scripts/upgrade.d/upgrade.$current_major_version.last.sh" ]; then
-			source $YNH_APP_BASEDIR/scripts/upgrade.d/upgrade.$current_major_version.last.sh
-			if dpkg --compare-versions "$gitlab_version" "gt" "$current_version"
-			then
-				return
-			fi
-		else
-			source $YNH_APP_BASEDIR/scripts/upgrade.d/upgrade.last.sh
-			if dpkg --compare-versions "$gitlab_version" "gt" "$current_version"
-			then
-				return
+		if [ -n "$next_version" ]; then
+			# Load this version
+			local version_id="v$(echo "$next_version" | tr '.' '_')"
+			if get_version_from_source_id "$version_id" "$gitlab_debian_version"; then
+				return 0
 			fi
 		fi
-		# Increment the major version to upgrade to the next version
-		if dpkg --compare-versions "$gitlab_version" "le" "$current_version"; then
-			current_major_version=$(($current_major_version + 1))
-			source_next_version
+
+		# If no next version found in current major, try next major
+		local next_major=$((current_major + 1))
+		versions=$(list_upgrade_versions "$next_major")
+
+		if [ -n "$versions" ]; then
+			# Get first version of next major
+			next_version=$(echo "$versions" | head -n1)
+			local version_id="v$(echo "$next_version" | tr '.' '_')"
+			if get_version_from_source_id "$version_id" "$gitlab_debian_version"; then
+				return 0
+			fi
 		fi
+
+		# Otherwise use latest
+		get_latest_version "$gitlab_debian_version"
 	}
 
-	# To upgrade GitLab from a major version A to a major version B,
+	# Get the latest version from manifest
+	get_latest_version "$gitlab_debian_version"
+	last_version=$gitlab_version
 
+	# To upgrade GitLab from a major version A to a major version B,
 	# we need to follow a specific path described here https://gitlab-com.gitlab.io/support/toolbox/upgrade-path/
 	# A.last -> B.first -> -> B.X -> B.Y -> B.last
 
@@ -157,20 +199,17 @@ then
 			sleep 1
 		done
 
-		current_major_version=${current_version%%.*}
-
 		source_next_version
 
 		ynh_print_info "Upgrade from ${current_version} to ${gitlab_version}"
 
-		ynh_config_add --template="$YNH_APP_BASEDIR/conf/$architecture.src.default" --destination="$YNH_APP_BASEDIR/conf/$architecture.src"
-
 		tempdir="$(mktemp -d)"
 
-		ynh_setup_source --dest_dir=$tempdir --source_id=$architecture
+		# Download using YunoHost's automatic architecture detection
+		ynh_setup_source --dest_dir=$tempdir --source_id="$gitlab_source_id"
 
-		if ! ynh_hide_warnings dpkg -i $tempdir/$gitlab_filename; then # This command will fail in lxc env
-			package_check_action # defined in upgrade.d/upgrade.X.sh
+		if ! ynh_hide_warnings dpkg -i $tempdir/gitlab-ce.deb; then # This command will fail in lxc env
+			package_check_action
 			ynh_hide_warnings dpkg --configure gitlab-ce
 		fi
 
@@ -179,22 +218,18 @@ then
 		current_version=$(grep gitlab-ce /opt/gitlab/version-manifest.txt | cut -d' ' -f2)
 
 		# Sometimes we need to update the gitlab.rb configuration file in order to migrate to the next version.
+		current_major_version=${current_version%%.*}
 		if [ -e "$YNH_APP_BASEDIR/conf/gitlab.$current_major_version.rb" ]; then
-			if [ -e "$YNH_APP_BASEDIR/scripts/upgrade.d/upgrade.$current_major_version.last.sh" ]; then
-				source $YNH_APP_BASEDIR/scripts/upgrade.d/upgrade.$current_major_version.last.sh
-			fi
-			if dpkg --compare-versions "$gitlab_version" "ge" "$current_version"; then
-				ynh_config_add --template="$YNH_APP_BASEDIR/conf/gitlab.$current_major_version.rb" --destination="$config_path/gitlab.rb"
+			ynh_config_add --template="$YNH_APP_BASEDIR/conf/gitlab.$current_major_version.rb" --destination="$config_path/gitlab.rb"
 
-				touch "$config_path/gitlab-persistent.rb"
-				#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown root:root "$config_path/gitlab-persistent.rb"
-				#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 640 "$config_path/gitlab-persistent.rb"
+			touch "$config_path/gitlab-persistent.rb"
+			chown root:root "$config_path/gitlab-persistent.rb"
+			chmod 640 "$config_path/gitlab-persistent.rb"
 
-				# During large migrations, the logs are too big to be sent to paste.yunohost.org
-				# Send the reconfigure logs in a file, and if the process succeeds, just delete it.
-				gitlab-ctl reconfigure > "/tmp/gitlab_upgrade_$current_version.log"
-				ynh_safe_rm "/tmp/gitlab_upgrade_$current_version.log"
-			fi
+			# During large migrations, the logs are too big to be sent to paste.yunohost.org
+			# Send the reconfigure logs in a file, and if the process succeeds, just delete it.
+			gitlab-ctl reconfigure > "/tmp/gitlab_upgrade_$current_version.log"
+			ynh_safe_rm "/tmp/gitlab_upgrade_$current_version.log"
 		fi
 	done
 fi
